"""Adds association table followers

Revision ID: 444efe26dd27
Revises: 720c30619ebe
Create Date: 2019-02-19 13:21:54.323116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444efe26dd27'
down_revision = '720c30619ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
